---
title: "MachineLearning-(C)"
author: "<Abdul Latif Fauzan>_<123190068>"
output:
  word_document: default
  html_document: default
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
library(dslabs)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(cluster)
library(factoextra)

df_Nilai = read.csv("DataPatSmaN1.csv", header=TRUE, sep=";")
```

## Bagian 1 Show Dataset
```{r }
df_Nilai
```


## Bagian 2 Pengelompokan Nilai yang mau dikluster
```{r }
df_NamaRata = select(df_Nilai,Urt,Nama,Matematika,Fisika.Geografi,Biologi.Ekonomi,Kimia.Sosiologi)
df_NamaRata
df_nama=df_NamaRata$Nama
df_nama
```

## Bagian 3 Menampilkan summary data apakah ada yang NA atau kosong
```{r }
summary(df_NamaRata)

```
## Bag 4 Mencari klustering terbaik menurut methode elbow dan silhouette
```{r }
tablefix=scale(df_NamaRata[,3:6])
##tablefix
fviz_nbclust(tablefix,kmeans,method="wss") ##methode elbow titik siku
fviz_nbclust(tablefix,kmeans) ##methode silhouette
```

## Bag 5 Mendapatkan nilai rata2 dan klustering
```{r }
final=kmeans(tablefix,2)
print(final)

fviz_cluster(final,data=tablefix)
final_akhir=data.frame(tablefix,final$cluster)
output=final_akhir%>%add_column(NamaSiswa=df_nama)
view(output)
```
## Bag 6 Memunculkan nilai klustering
```{r }
df_NamaRata[,3:6]%>%
  mutate(Cluster=final$cluster)%>%
  group_by(Cluster)%>%
  summarise_all("mean")

```